services:
  mono-earthquake:
    build:
      context: .
      dockerfile: Dockerfile
    image: mono-earthquake:latest
    container_name: mono-earthquake
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./data:/mono-earthquake/data
      - ./logs:/mono-earthquake/logs
    environment:
      - PORT=${PORT}
      - POLL_INTERVAL=${POLL_INTERVAL}
    restart: unless-stopped
